[package]
name = "xtask"
version = "0.1.0"
edition = "2018"
publish = false

[features]
default = ["isahc", "semver", "toml_edit"]

[dependencies]
isahc = { version = "1.2.0", features = ["json"], optional = true }
semver = { version = "1.0.4", features = ["serde"], optional = true }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
toml = "0.5.8"
toml_edit = { version = "0.6.0", optional = true }
xflags = "0.2.1"
xshell = "0.1.9"
