[package]
name = "ruma-common"
version = "0.8.0"
description = "Common types for other ruma crates."
homepage = "https://www.ruma.io/"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/ruma/ruma"
edition = "2018"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
compat = []
unstable-exhaustive-types = []
unstable-pre-spec = []
unstable-msc2677 = []

[dependencies]
indexmap = { version = "1.6.2", features = ["serde-1"] }
js_int = { version = "0.2.0", features = ["serde"] }
ruma-identifiers = { version = "0.22.0", path = "../ruma-identifiers" }
ruma-serde = { version = "0.6.0", path = "../ruma-serde" }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = { version = "1.0.60", features = ["raw_value"] }
tracing = "0.1.25"
wildmatch = "2.0.0"

[dev-dependencies]
maplit = "1.0.2"
matches = "0.1.8"
