name: Rust Stable

on:
  push:
    branches: [main, next]
  pull_request:
    branches: [main, next]

jobs:
  check_stable:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Run checks
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p xtask --no-default-features ci stable
